### ISSUE TITLE
Pass java arguments?

### ISSUE THREAD

**Issue by Vixeliz** [liabri/rimca#10]
Is their currently anyway to specify custom java arguments. Preferably per instance but overall is also fine. If not and it's something your interested in I may be able to implement it.

**Comment by Vixeliz** [comment]
At least temporary I threw together just some arguments at the end of the launch command https://github.com/Vixeliz/rimca (ignore the crappy commits forgot to get rid of logs probably should be in gitignore)

**Comment by liabri** [comment]
I will have a look at it tomorrow as I am not home, however, you should be able to add jvm arguments through the state.json file within the instance folder. 


9 Jul 2023, 00:58 by ***@***.***:

**Comment by Vixeliz** [comment]
Ah my bad thanks for the response
